name: publish-stable-aws

on:
  push:
    branches:
      - '**'
jobs:
  push-to-gitops-integration:
    runs-on: ubuntu-latest
    steps:
      - name: 'pwd'
        run: pwd
      - name: 'ls'
        run: ls
      - name: 'Install bazel 3.2.0'
        run: sudo apt update && sudo apt install bazel-3.2.0
      - name: 'Install docker pre requisite packages'
        run: sudo apt-get install curl apt-transport-https ca-certificates software-properties-common
      - name: 'Install docker'
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
          sudo apt update
          apt-cache policy docker-ce
          sudo apt install docker-ce
      - name: 'Clone integration repo'
        env:
          INTEGRATION_GITHUB_TOKEN: ${{ secrets.INTEGRATION_GITHUB_TOKEN }}
        run: git clone https://dhasuda:$INTEGRATION_GITHUB_TOKEN@github.com/dhasuda/k8s-gitops-test
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: dhasuda
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build
        run: |
          pwd
          ls
          bazel run //:platform --experimental_ui_limit_console_output=1 | tee k8s-gitops-test/control_plane.yaml
      - name: Push changes
        run: |
          cd k8s-gitops-test
          git config user.name "dhauda"
          git config user.email $INTEGRATION_GITHUB_EMAIL
          git add control_plane.yaml
          git commit -m "New release"
          git push --set-upstream https://dhasuda:$INTEGRATION_GITHUB_TOKEN@github.com/dhasuda/k8s-gitops-test
        env:
          INTEGRATION_GITHUB_TOKEN: ${{ secrets.INTEGRATION_GITHUB_TOKEN }}
          GITHUB_EMAIL: ${{ secrets.INTEGRATION_GITHUB_EMAIL }}
